// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HandlerEngine.SourceGenerator.Templates
{
    using HandlerEngine.SourceGenerator.CollectableData;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ServiceClientTemplate : ServiceClientTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Buffers.Binary;\r\nusing System.Collections.Generic;\r\nusing System.Collections.Concurrent;\r\nusing System.Threading;\r\nusing System.Threading.Tasks;\r\n\r\nusing HandlerEngine;\r\nusing HandlerEngine.Interfaces;\r\nusing HandlerEngine.Serialization;\r\n\r\n");
            
            #line 14 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

    if(Info.HasNamespace)
    {

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 18 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Info.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 20 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

        PushIndent("\t");
    }

    bool hasRpc = Info.HasRpc();

            
            #line default
            #line hidden
            this.Write("public sealed class ");
            
            #line 26 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Info.ServiceName));
            
            #line default
            #line hidden
            this.Write("Client : ");
            
            #line 26 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(hasRpc ? $"{Info.ServiceName}RpcClient, " : string.Empty));
            
            #line default
            #line hidden
            this.Write("I");
            
            #line 26 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Info.ServiceName));
            
            #line default
            #line hidden
            this.Write("Client\r\n{\r\n    private readonly RequestResponseDelegate[] _handlers;\r\n\r\n");
            
            #line 30 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

    if(!hasRpc)
    {

            
            #line default
            #line hidden
            this.Write("    public string ServiceName => \"");
            
            #line 34 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Info.ServiceName));
            
            #line default
            #line hidden
            this.Write("\";\r\n    public byte ServiceId { get; private set; }\r\n    public INetRecipient Recipient { get; private set; }\r\n\r\n    void IServiceUnit.Bind(INetRecipient recipient, byte serviceId)\r\n    {\r\n        ServiceId = serviceId;\r\n        Recipient = recipient;\r\n    }\r\n");
            
            #line 43 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n    public void HandleResponseAsync(byte actionIdx, OperationCode operationCode, short requestNumber, ref ReadOnlySpan<byte> data)\r\n    {\r\n        _handlers[actionIdx].Invoke(operationCode, requestNumber, ref data);\r\n    }\r\n\r\n    IEnumerable<ServiceActionDescription> IReceiverServiceUnit.Actions()\r\n    {\r\n");
            
            #line 54 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

    if(Info.MethodInfos.Length == 0)
    {

            
            #line default
            #line hidden
            this.Write("        yield break;\r\n");
            
            #line 59 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

    }
    else
    {
        var handlerIdx = 0;
        for(var i = 0; i < Info.MethodInfos.Length; ++i)
        {
            MethodInfo action = Info.MethodInfos[i];
            if(action.IsRpc())
            {
                continue;
            }

            
            #line default
            #line hidden
            this.Write("        yield return new ServiceActionDescription(0x");
            
            #line 72 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.CallAttributeInfo.CallId.ToString("X2")));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 72 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(handlerIdx++));
            
            #line default
            #line hidden
            this.Write(", true);\r\n");
            
            #line 73 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

        }

        if(handlerIdx == 0)
        {

            
            #line default
            #line hidden
            this.Write("        yield break;\r\n");
            
            #line 80 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n    public ");
            
            #line 86 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Info.ServiceName));
            
            #line default
            #line hidden
            this.Write("Client()\r\n    {\r\n");
            
            #line 88 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

    if(Info.MethodInfos.Length == 0 || Info.MethodInfos.All(info => info.IsRpc()))
    {

            
            #line default
            #line hidden
            this.Write("        _handlers = Array.Empty<RequestResponseDelegate>();\r\n");
            
            #line 93 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

    }
    else
    {

            
            #line default
            #line hidden
            this.Write("        _handlers = new RequestResponseDelegate[]\r\n        {\r\n");
            
            #line 100 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

        for(var i = 0; i < Info.MethodInfos.Length; ++i)
        {
            MethodInfo action = Info.MethodInfos[i];
            if(action.IsRpc())
            {
                continue;
            }

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 109 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name));
            
            #line default
            #line hidden
            this.Write("_Response0x");
            
            #line 109 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.CallAttributeInfo.CallId.ToString("X2")));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 110 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("        };\r\n");
            
            #line 114 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("    }\r\n");
            
            #line 118 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

    var count = 0;
    foreach(MethodInfo mi in Info.MethodInfos)
    {
        if(mi.IsRpc())
        {
            continue;
        }

        ResponseMethodInfo rmi = mi.ToResponse();

        if(count++ > 1)
        {
            WriteLine(string.Empty);
        }

        //Request number field name
        string rnfn = $"_{mi.CallAttributeInfo.CallId:X2}_rn";

            
            #line default
            #line hidden
            this.Write("\r\n    private int ");
            
            #line 138 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rnfn));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n    private ConcurrentDictionary<short, TaskCompletionSource<");
            
            #line 140 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmi.ReturnType));
            
            #line default
            #line hidden
            this.Write(">> _");
            
            #line 140 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mi.CallAttributeInfo.CallId.ToString("X2")));
            
            #line default
            #line hidden
            this.Write("_tcs = new();\r\n\r\n    public Task<");
            
            #line 142 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmi.ReturnType));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 142 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmi.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 142 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmi.RequestArguments.Inline(true)));
            
            #line default
            #line hidden
            this.Write(")\r\n    {\r\n        int __new_");
            
            #line 144 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rnfn));
            
            #line default
            #line hidden
            this.Write(", __old_");
            
            #line 144 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rnfn));
            
            #line default
            #line hidden
            this.Write(";\r\n        do\r\n        {\r\n            __old_");
            
            #line 147 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rnfn));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 147 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rnfn));
            
            #line default
            #line hidden
            this.Write(";\r\n            __new_");
            
            #line 148 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rnfn));
            
            #line default
            #line hidden
            this.Write(" = (__old_");
            
            #line 148 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rnfn));
            
            #line default
            #line hidden
            this.Write(" + 1) & 0x7FFF;\r\n        }\r\n        while (Interlocked.CompareExchange(ref ");
            
            #line 150 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rnfn));
            
            #line default
            #line hidden
            this.Write(", __new_");
            
            #line 150 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rnfn));
            
            #line default
            #line hidden
            this.Write(", __old_");
            
            #line 150 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rnfn));
            
            #line default
            #line hidden
            this.Write(") != __old_");
            
            #line 150 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rnfn));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n        var __opCode = new OperationCode(ServiceId, 0x");
            
            #line 152 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mi.CallAttributeInfo.CallId.ToString("X2")));
            
            #line default
            #line hidden
            this.Write(");\r\n        var __requestNumber = (short)__new_");
            
            #line 153 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rnfn));
            
            #line default
            #line hidden
            this.Write(";\r\n        var __buffer = WriterBufferPool.Buffer;\r\n        \r\n        BinaryPrimitives.WriteUInt16LittleEndian(__buffer.GetSpan(sizeof(ushort)), __opCode.OpCode);\r\n\t\t__buffer.Advance(sizeof(ushort));\r\n\t\tBinaryPrimitives.WriteInt16LittleEndian(__buffer.GetSpan(sizeof(short)), __requestNumber);\r\n\t\t__buffer.Advance(sizeof(short));\r\n\r\n");
            
            #line 161 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

        foreach(MethodArgumentInfo methodArgumentInfo in rmi.RequestArguments)
        {

            
            #line default
            #line hidden
            this.Write("        HandlerEngineSerializer.Serializer.Write(ref __buffer, ");
            
            #line 165 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodArgumentInfo.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 166 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("        var __tcs = new TaskCompletionSource<");
            
            #line 169 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmi.ReturnType));
            
            #line default
            #line hidden
            this.Write(">();\r\n        _");
            
            #line 170 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mi.CallAttributeInfo.CallId.ToString("X2")));
            
            #line default
            #line hidden
            this.Write("_tcs[__requestNumber] = __tcs;\r\n\r\n        var __writtenSpan = __buffer.WrittenSpan;\r\n        Recipient!.Send(ref __writtenSpan, ");
            
            #line 173 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mi.CallAttributeInfo.ChannelType.InlineChanelType()));
            
            #line default
            #line hidden
            this.Write(",  ");
            
            #line 173 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mi.CallAttributeInfo.ChannelId.ToString()));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n        return __tcs.Task;\r\n    }\r\n\r\n    private void ");
            
            #line 178 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmi.Name));
            
            #line default
            #line hidden
            this.Write("_Response0x");
            
            #line 178 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmi.CallAttributeInfo.CallId.ToString("X2")));
            
            #line default
            #line hidden
            this.Write("(OperationCode __operationCode, short __requestNumber, ref ReadOnlySpan<byte> __data)\r\n    {\r\n");
            
            #line 180 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

        foreach(MethodArgumentInfo mai in rmi.ResponseArguments)
        {

            
            #line default
            #line hidden
            this.Write("        var ");
            
            #line 184 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mai.Name));
            
            #line default
            #line hidden
            this.Write(" = HandlerEngineSerializer.Deserializer.Read<");
            
            #line 184 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mai.Type));
            
            #line default
            #line hidden
            this.Write(">(ref __data);\r\n");
            
            #line 185 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

        }
        if(rmi.ReturnIsTuple)
        {

            
            #line default
            #line hidden
            this.Write("        var __result = (");
            
            #line 190 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmi.ResponseArguments.Inline(false, false)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 191 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("        if(_");
            
            #line 194 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(mi.CallAttributeInfo.CallId.ToString("X2")));
            
            #line default
            #line hidden
            this.Write("_tcs.Remove(__requestNumber, out var __tcs))\r\n        {\r\n");
            
            #line 196 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

        if(rmi.ReturnIsTuple)
        {

            
            #line default
            #line hidden
            this.Write("            __tcs.SetResult(__result);\r\n");
            
            #line 201 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("            __tcs.SetResult(");
            
            #line 206 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmi.ResponseArguments[0].Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 207 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("        }\r\n        else\r\n        {\r\n            throw new InvalidOperationException($\"Unknown request number: {{__requestNumber}} in ");
            
            #line 213 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rmi.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n        }\r\n    }\r\n");
            
            #line 216 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 220 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

    if(Info.HasNamespace)
    {
        PopIndent();

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 226 "E:\Projects\Unity\FrameProject\mmog\mmog_backend\HandlerEngine.SourceGenerator\Templates\ServiceClientTemplate.tt"

    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ServiceClientTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
